name: PageSpeed Insights Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pagespeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run-pagespeed
        id: run-pagespeed
        uses: ./
        with:
          url: 'https://www.ibjapan.com/'
          key: ${{ secrets.GOOGLE_PSI }}

      - name: Output PageSpeed Metrics
        run: |
          echo "デスクトップのパフォーマンス: ${{ steps.run-pagespeed.outputs.desktop_score }}"
          echo "デスクトップのLCP: ${{ steps.run-pagespeed.outputs.desktop_largest-contentful-paint }}"
          echo "デスクトップのCLS: ${{ steps.run-pagespeed.outputs.desktop_cumulative-layout-shift }}"
          echo "デスクトップのFCP: ${{ steps.run-pagespeed.outputs.desktop_first-contentful-paint }}"
          echo "デスクトップのTBT: ${{ steps.run-pagespeed.outputs.desktop_total-blocking-time }}"
          echo "デスクトップのSI: ${{ steps.run-pagespeed.outputs.desktop_speed-index }}"

          echo "モバイルのパフォーマンス: ${{ steps.run-pagespeed.outputs.mobile_score }}"
          echo "モバイルのLCP: ${{ steps.run-pagespeed.outputs.mobile_largest-contentful-paint }}"
          echo "モバイルのCLS: ${{ steps.run-pagespeed.outputs.mobile_cumulative-layout-shift }}"
          echo "モバイルのFCP: ${{ steps.run-pagespeed.outputs.mobile_first-contentful-paint }}"
          echo "モバイルのTBT: ${{ steps.run-pagespeed.outputs.mobile_total-blocking-time }}"
          echo "モバイルのSI: ${{ steps.run-pagespeed.outputs.mobile_speed-index }}"
