name: PageSpeed Insights Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pagespeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run-pagespeed
        id: run-pagespeed
        uses: ./
        with:
          url: 'https://www.ibjapan.com/'
          key: ${{ secrets.GOOGLE_PSI }}

      - name: Output PageSpeed Metrics
        run: |
          echo "パフォーマンス: ${{ steps.run-pagespeed.outputs.desktop-score }}"
          echo "LCP: ${{ steps.run-pagespeed.outputs.desktop-largest-contentful-paint }}"
          echo "CLS: ${{ steps.run-pagespeed.outputs.desktop-cumulative-layout-shift }}"
          echo "FCP: ${{ steps.run-pagespeed.outputs.desktop-first-contentful-paint }}"
          echo "TBT: ${{ steps.run-pagespeed.outputs.desktop-total-blocking-time }}"
          echo "SI: ${{ steps.run-pagespeed.outputs.desktop-speed-index }}"
