name: PageSpeed Insights Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-pagespeed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run-pagespeed
        id: run-pagespeed
        uses: ./
        with:
          url: 'https://www.ibjapan.com/'
          key: ${{ secrets.GOOGLE_PSI }}

      - name: Output PageSpeed Metrics
        run: |
          echo "デスクトップ メトリクス"
          echo "デスクトップ パフォーマンス: ${{ steps.run-pagespeed.outputs.desktop-score }}"
          echo "デスクトップ LCP: ${{ steps.run-pagespeed.outputs.desktop-largest-contentful-paint }}"
          echo "デスクトップ CLS: ${{ steps.run-pagespeed.outputs.desktop-cumulative-layout-shift }}"
          echo "デスクトップ FCP: ${{ steps.run-pagespeed.outputs.desktop-first-contentful-paint }}"
          echo "デスクトップ TBT: ${{ steps.run-pagespeed.outputs.desktop-total-blocking-time }}"
          echo "デスクトップ SI: ${{ steps.run-pagespeed.outputs.desktop-speed-index }}"
          echo "***************************************************************"
          echo "モバイル メトリクス"
          echo "モバイル パフォーマンス: ${{ steps.run-pagespeed.outputs.mobile-score }}"
          echo "モバイル LCP: ${{ steps.run-pagespeed.outputs.mobile-largest-contentful-paint }}"
          echo "モバイル CLS: ${{ steps.run-pagespeed.outputs.mobile-cumulative-layout-shift }}"
          echo "モバイル FCP: ${{ steps.run-pagespeed.outputs.mobile-first-contentful-paint }}"
          echo "モバイル TBT: ${{ steps.run-pagespeed.outputs.mobile-total-blocking-time }}"
          echo "モバイル SI: ${{ steps.run-pagespeed.outputs.mobile-speed-index }}"
